HDA-3738 android-style-guide 저장소 최신화 - Clean Architecture
PRNDcompany/android-style-guide pull request #10
Opened 2021-09-23 09:06 UTC by olaf-prnd

큰 수정없이 Notion에는 있고 GitHub 저장소에는 없는 부분들만 추가했습니다.

## 수정사항
- `:`을 쓰는 라인에서 개행이 이루어지지 않아 `-`로 변경했습니다.
- **XXXLocal**의 예시 부분을 조금 더 이해하기 쉽게 User의 email로 변경하였습니다.

2021-09-23 09:20 UTC, ted-prnd requested changes

2021-09-23 09:20 UTC, ted-prnd commented on Architecture.md
> +  - User에 email이 추가되어야함
예시는
```
```
포맷으로 동일하게 적용해주세요

2021-09-24 02:07 UTC, olaf-prnd commented on Architecture.md
> +  - User에 email이 추가되어야함
dd4d39d

2021-09-24 02:11 UTC, ted-prnd approved these changes
LGTM 👍:ok_woman::pray::computer:

2021-09-24 02:12 UTC, merged