HDA-3740 android-style-guide 저장소 최신화 - Xml, Resource
PRNDcompany/android-style-guide pull request #11
Opened 2021-09-23 09:12 UTC by olaf-prnd

Xml, Resource 문서 모두 큰 내용이 없어서 누락된 내용들만 Resource.md 파일에 추가해주었습니다.

Xml 문서는 별도의 문서로 만들지 않고 기존 Resource.md 파일에 해당 내용이 있어서 누락된 내용만 추가해주었습니다.
imgbot은 현재 사용하지 않고 있어서 tinypng 관련 내용을 유지하였습니다.

2021-09-23 09:22 UTC, ted-prnd requested changes

2021-09-23 09:22 UTC, ted-prnd commented on Resource.md
>  - `img_xxx`의 경우 파일의 크기가 큰경우가 많으므로 [tinypng](https://tinypng.com/)에서 파일크기를 줄인뒤에 추가 해주어야 한다.
(GitHub imgbot을 사용한다면 생략 가능, https://github.com/marketplace/imgbot) 을 추가해주세요

2021-09-24 02:12 UTC, olaf-prnd commented on Resource.md
>  - `img_xxx`의 경우 파일의 크기가 큰경우가 많으므로 [tinypng](https://tinypng.com/)에서 파일크기를 줄인뒤에 추가 해주어야 한다.
4521f17

2021-09-24 02:15 UTC, ted-prnd approved these changes
LGTM 👍:ok_woman::pray::computer:

2021-09-24 02:17 UTC, merged